### ISSUE TITLE
Support for Proxy Models

### ISSUE THREAD

**Issue by jm2242** [graphql-python/graphene-django#319] opened 2017-11-06 05:14 UTC
Is there support for querying proxy models? I'm trying to query a model that has a bunch of proxy models but am getting an error. Here's an abbreviated look at my setup:
```
class Column:
...

class FieldColumn(Column):
  proxy=True
```

```
class Query(graphene.ObjecType):
    column = graphene.Field(ColumnType)
    all_columns = DjangoFilterConnectionField(ColumnType)
```

and 
```
class ColumnType(DjangoObjectType):
    class Meta:
        model = Column
        filter_fields = ['sheet__name', 'name']
        interfaces = (relay.Node, )
        exclude_fields = [  
            'legislation_type', 'project_stat_type', ... # weirdly have to exclude these fields because the 'type' in the variable name makes the field introspector sad
        ]
```

my query is:
```
query {
	allColumns(sheet_Name:"Simple Sheet") {
		edges {
      node{
        id, name
      }
    }
  }
}
```

Here's the trace:
```
Traceback (most recent call last):
  File "/Users/jonathanmares/.virtualenvs/quorum/lib/python2.7/site-packages/promise/promise.py", line 65, in try_catch
    return (handler(*args, **kwargs), None)
  File "/Users/jonathanmares/.virtualenvs/quorum/lib/python2.7/site-packages/graphql/execution/executor.py", line 375, in <lambda>
    resolved
  File "/Users/jonathanmares/.virtualenvs/quorum/lib/python2.7/site-packages/graphql/execution/executor.py", line 405, in complete_value
    return complete_object_value(exe_context, return_type, field_asts, info, result)
  File "/Users/jonathanmares/.virtualenvs/quorum/lib/python2.7/site-packages/graphql/execution/executor.py", line 499, in complete_object_value
    field_asts
graphql.error.base.GraphQLError: Expected value of type "ColumnType" but got: FieldColumn.
```

I know this PR https://github.com/graphql-python/graphene-django/pull/156/files is waiting to be merged, but I tried running my query with the proposed changes and still get the same error.

**Comment by spockNinja** [comment] 2017-11-15 06:27
Following that traceback, I think the root of the problem is [here](https://github.com/graphql-python/graphene-django/blob/master/graphene_django/types.py#L111-L112).

We are checking for `_meta.model` to match between the actual returned object and the model assigned in the DjangoObjectType meta.

So I think to support proxy models, we might want to check `_meta.model._meta.concrete_model` instead? I'm not sure on the django version support for `concrete_model`, but if it has always been there, that just might work. Otherwise, we might have to check `_meta.model._meta.proxy` and handle that case specially.

**Comment by spockNinja** [comment] 2017-11-15 06:33
I went back through django source to 1.7, and it looks like `concrete_model` has always been there. Would you like to whip up a Pull Request with that change and see if it solves the problem for you?

**Comment by jm2242** [comment] 2017-11-16 05:33
excellent! that was it, thanks for your help. I'll get a PR up with a test or two and some docs

**Comment by serates** [comment] 2018-01-13 00:09
@jm2242 Did you get this PR up? If so could you link it here so i could follow it since my issue should also be fixed by this PR.

**Comment by jm2242** [comment] 2018-01-13 16:09
I have not, but I will do this today or tomorrow!

**Comment by filipeximenes** [comment] 2018-10-08 23:58
Did this get fixed?

**Comment by jm2242** [comment] 2018-10-09 01:44
Yes I believe this PR does address this, at least basic support https://github.com/graphql-python/graphene-django/pull/373

**Comment by filipeximenes** [comment] 2018-10-09 01:57
@jm2242 thanks for getting back. I just noticed that it was failing for me because I was trying to use it in model relationship and at the model level I was defining the relationship through the proxy model. So if someone finds this, just make sure you don't use proxy models in the `ForeignKey`s of your models. 
Not super urgent, but should we treat this as bug? As in, should graphene know how to handle this case?

**Comment by jm2242** [comment] 2018-10-09 04:42
Maybe post a minimal example, and someone can pick it up and fix it?

**Comment by filipeximenes** [comment] 2019-03-22 11:31
A bit late but the example would be:
```
class Model1(models.Model):
     ....

class ProxyModel1(Model1):
    ....
    class Meta:
        proxy = True

class Model2(models.Model):
    relationship = models.ForeignKey(ProxyModel1)
    ....
```

**Comment by zbyte64** [comment] 2019-03-22 19:26
The test case currently has an `Article` that has a foreign key to a proxy model `Reporter`

Currently at:
https://github.com/graphql-python/graphene-django/blob/ea2cd9894fa1c8a65c365d1b7c042e27df519324/graphene_django/tests/test_query.py#L896

To match the example given here they foreign key would be adjusted to `CNNReporter`

**Comment by abettke** [comment] 2019-03-27 04:15
IRT #599, I've added a [PR](#603 ) to try and better address this issue.

**Comment by dopeboy** [comment] 2019-05-08 06:11
Let's take this over to #603, thanks all.

**Closed by dopeboy** 2019-05-08 06:11 UTC
