### ISSUE TITLE
DjangoFilterConnectionField seems to disregard filtered queryset

### ISSUE THREAD

**Issue by jole78** [graphql-python/graphene-django#90] opened 2017-01-16 06:34 UTC
Given the following code:

```python
class Report(DjangoObjectType):
	class Meta:
		model = ReportModel
		interfaces = (graphene.Node, )
		filter_fields = {
			'state': ['exact'],
		}

class Query(graphene.AbstractType):
	reports = DjangoFilterConnectionField(Report)

	def resolve_reports(self, args, context, info):
		return ReportModel.objects.filter(created_by=context.user)
```

When I issue the following query:

```
{
  reports(state: "draft") {
    edges {
      node {
        id
        state        
      }
    }
  }
  __debug {
    sql {
      raw_sql
      params
    }
  }
}
```

I get the following:

```
          "raw_sql": "SELECT COUNT(*) AS \"__count\" FROM \"myapp_report\" WHERE \"myapp_report\".\"created_by_id\" = %s",
          "params": "[3]"
```

You can see that it disregards the filter altogether. 

However, if I remove this from the the query:
```python
	def resolve_reports(self, args, context, info):
		return ReportModel.objects.filter(created_by=context.user)
```

I get the desired result, but then the query is not filtered by user access any more.

Result:
```
      "sql": [
        {
          "raw_sql": "SELECT COUNT(*) AS \"__count\" FROM \"myapp_report\" WHERE \"myapp_report\".\"state\" = %s",
          "params": "[\"draft\"]"
        },
```

Am I doing something wrong here or is it a bug? Please advise.

**Comment by jole78** [comment] 2017-01-16 06:49
Update:

OK, this actually seems to be working again if apply the line that this PR adds to DjangoConnectionField.
https://github.com/graphql-python/graphene-django/pull/82

When can we expect this version to be on PyPI??

**Comment by crucialfelix** [comment] 2017-03-17 08:48
Duplicate of https://github.com/graphql-python/graphene-django/issues/30

fix not yet released

**Closed** 2019-03-19 17:27 UTC
