### ISSUE TITLE
Make graphiql work offline

### ISSUE THREAD

**Issue by matclayton** [graphql-python/graphene-django#271] opened 2017-09-13 21:06 UTC
Currently graphiql depends on a cdn copy of react and other libraries, this makes graphiql useless in an offline situation.

Sorry if this isn’t specifically a graphene-django issue.

**Comment by clodal** [comment] 2017-09-22 12:32
I don't think it is a graphen django issue though

**Comment by saschalalala** [comment] 2018-05-31 18:34
I think it is, because the template is part of this project, see https://github.com/graphql-python/graphene-django/blob/master/graphene_django/templates/graphene/graphiql.html#L19

**Comment by zbyte64** [comment] 2019-03-20 01:27
Duplicate of #69

**Closed by zbyte64** 2019-03-20 01:27 UTC
