### ISSUE TITLE
Is there any way to get select_related to work?

### ISSUE THREAD

**Issue by camd** [graphql-python/graphene-django#197] opened 2017-06-07 00:10 UTC
I can't seem to get ``select_related`` to be honored at all, in my experience.  Can anyone help me identify how it should work?

``Job`` has a foreign keys to ``Push`` and to ``FailureClassification`` models.
Here's my Graphene Schema:

    class PushGraph(DjangoObjectType):
        class Meta:
            model = Push
            filter_fields = ('revision', )
            interfaces = (graphene.relay.Node, )
    
        jobs = DjangoFilterConnectionField(JobGraph)
    
        def resolve_jobs(self, args, context, info):
            return (Job.objects
                .filter(push=self, **args)
                .select_related("failure_classification")
            )

This seems to have no effect on doing a join in the queries.  I get tons of repeat queries for each ``Job`` that's returned.  Is this a bug?  Or a result of using ``DjangoFilterConnectionField``? as mentioned in Issue 179?

Thanks!

**Comment by japrogramer** [comment] 2017-08-08 19:54
My guess is that you need a data loader so that your repeat queries now that the data has already been fetched. http://docs.graphene-python.org/en/latest/execution/dataloader/

**Comment by ramusus** [comment] 2017-08-17 20:16
Duplicate of https://github.com/graphql-python/graphene-django/issues/179

**Comment by BossGrand** [comment] 2017-11-03 19:31
@ramusus this is actually not a duplicate because #179 uses DjangoConnectionField and this issue uses DjangoFilterConnectionField which have distinct merge_queries functions

**Closed** 2017-11-13 10:22 UTC

**Comment by ramusus** [comment] 2017-11-19 00:04
@syrusakbary I don't see these changes in v2.0.0. Did you publish a new version on the pypi ?
