### ISSUE TITLE
Filtering using Django Integer Choices

### ISSUE THREAD

**Issue by robertpro** [graphql-python/graphene-django#649] opened 2019-05-24 03:56 UTC
Hey guys, I am a real noob with GraphQL, but I think I found a bug, I am trying to filter using an integer choice, below you will see the definitions:

*models.py*
```python
class Event(models.Model):
    KIND_XXX = 1
    KIND_CHOICES = (
        (KIND_XXX, "Dummy description"),
    )
    name = models.CharField(max_length=35)
    kind = models.IntegerField(choices=KIND_CHOICES)
```

*schema.py*
```python
class EventNode(DjangoObjectType):
    class Meta:
        model = Event
        filter_fields = {
            'name': ['exact', 'in', 'icontains', 'istartswith'],
            'kind': ['exact', 'in', 'icontains', 'istartswith'],
        }
        interfaces = (graphene.relay.Node,)

class Query(graphene.ObjectType):
    event = graphene.relay.Node.Field(EventNode)
    all_events = DjangoFilterConnectionField(EventNode)
```

If I query using `name`, `name__in`, etc it works, but when I try to filter by `kind__in` it says I need an `Float` which is wrong.

Please note the Float there:
![image](https://user-images.githubusercontent.com/8595170/58301460-23347c80-7dac-11e9-99ab-196a491047cb.png)

Result:
```json
{
  "errors": [
    {
      "message": "Argument \"kind_In\" has invalid value \"1\".\nExpected type \"Float\", found \"1\".",
      "locations": [
        {
          "line": 2,
          "column": 22
        }
      ]
    }
  ]
}
```

As a second help request, I found other issue (but I am not sure if I am misunderstanding something) if I query for a not existent `kind` it returns the information:

*Query for all records...*

```graphql
query{
  allEvents{
    edges{
      node{
        kind
        name
      }
    }
  }
}
```

*Result for all records*
```json
{
  "data": {
    "allEvents": {
      "edges": [
        {
          "node": {
            "kind": "A_1",
            "name": "Event X"
          }
        }
      ]
    }
  }
}
```

*Query for not existent kind choice*
```graphql
query{
  allEvents(kind: "2"){
    edges{
      node{
        kind
        name
      }
    }
  }
}
```

*Result for not existent kind choice*

```json
{
  "data": {
    "allEvents": {
      "edges": [
        {
          "node": {
            "kind": "A_1",
            "name": "Event X"
          }
        }
      ]
    }
  }
}
```

I spent like 8 hours debugging, but I couldn't find any solution, if you can address for a solution, I can PR the fix (in case it is really a bug..,)

Thanks!

**Comment by zbyte64** [comment] 2019-05-24 16:42
Try removing the quotes in `kind_In: "1"`

**Comment by robertpro** [comment] 2019-05-24 17:15
@zbyte64 thank you for checking my issue, that does not work either :(

```graphql
query{
  allEvents(kind_In: 1){
    edges{
      node{
        kind
        name
      }
    }
  }
}
```

Result:
```json
{
  "errors": [
    {
      "message": "'float' object has no attribute 'split'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "allEvents"
      ]
    }
  ],
  "data": {
    "allEvents": null
  }
}
```

This is the error on the console:

```bash
graphql.error.located_error.GraphQLLocatedError: 'float' object has no attribute 'split'
```

Which makes sense, it is *really* expecting a string, not a Float

For extra information, when I was debugging I realized that the exception was raised [here](https://github.com/carltongibson/django-filter/blob/1f47e36b614724a8735e0457fa511dcaf5448481/django_filters/widgets.py#L201), I have no idea how it went to [BaseCSVWidget classt](https://github.com/carltongibson/django-filter/blob/1f47e36b614724a8735e0457fa511dcaf5448481/django_filters/widgets.py#L191)

**Comment by zbyte64** [comment] 2019-05-24 19:40
Ahh, then try: `kind_In: [1]`
It needs to be a list of numbers.

**Comment by robertpro** [comment] 2019-05-24 19:45
Unfortunately that is not working either:
![image](https://user-images.githubusercontent.com/8595170/58352846-6f2a0480-7e32-11e9-8b88-16a15f936773.png)

*Result*

```json
"message": "Argument \"kind_In\" has invalid value [1].\nExpected type \"Float\", found [1]."
```

It still asking for a Float, which I think is the bug

**Comment by robertpro** [comment] 2019-05-24 19:47
Same with other tries:
["1", "2"]
["1,2"]

**Comment by zbyte64** [comment] 2019-05-24 19:52
Asking for a Float is definitely not right. Trying to find where that is specified atm. Another thing to try would be: `[1. , 2.]`

**Comment by zbyte64** [comment] 2019-05-24 20:02
My best guess is that `converter.convert_django_file_with_choices` is not properly configuring the type in graphene. What is going on behind the scenes is that specifying a `choices` currently converts the field type to an Enum. Looking at our unit tests, we check for an Enum type but we do not validate the value subtype (I am not sure where that is accessed atm). We should start by writing a specific test (under `tests.test_converter`) with an IntegerField with choices.

**Comment by robertpro** [comment] 2019-05-24 20:11
All tries were running without success:

[1., 2.] - Results in:

```json
"Syntax Error GraphQL (2:25) Invalid number, expected digit but got: \",\".\n\n1: query{\n2:   allEvents(kind_In: [1., 2.]){\n                           ^\n3:     edges{\n"
```

[1.0, 2.0] - Results in:

```json
"Argument \"kind_In\" has invalid value [1.0, 2.0].\nExpected type \"Float\", found [1.0, 2.0]."
```

**Comment by robertpro** [comment] 2019-05-25 01:19
This is what I tried:

**test_converter.py** based on this [test](https://github.com/graphql-python/graphene-django/blob/e6ad5887caebf818b0c61d09924c51a9f0f9b406/graphene_django/tests/test_converter.py#L151)
```python
def test_field_with_integer_choices_convert_enum():
    field = models.IntegerField(
        help_text="Status", choices=((1, "Active"), (2, "Inactive"))
    )

    class StatusModel(models.Model):
        status = field

        class Meta:
            app_label = "test"

    graphene_type = convert_django_field_with_choices(field)
    assert isinstance(graphene_type, graphene.Enum)  # pdb here (with Pycharm)
```

I couldn't find any place where the type/subtype were `Float`, under [convert_django_field_with_choices](https://github.com/graphql-python/graphene-django/blob/54ef52e1c63f96888df4c23d4775186a33fb7416/graphene_django/converter.py#L55).

So I tried to get the base class of the member without success, this is how I tried access:

```python
graphene_type._meta.enum.__members__['A_1']
#type: EnumMeta
```

**Attributes**
![image](https://user-images.githubusercontent.com/8595170/58362760-98fa2000-7e60-11e9-9f91-5d6d070205cb.png)

```python
from graphene.types.base import BaseType
from graphene.pyutils.init_subclass import InitSubclassMeta

isinstance(graphene_type._meta.enum.__members__['A_1'], BaseType)  # Returns False
isinstance(graphene_type._meta.enum.__members__['A_1'], InitSubclassMeta)  # Returns False
```

Unfortunately I don't have any other idea/knowledge to test, if you need any other information or idea I will try to help ASAP.

**Comment by zbyte64** [comment] 2019-05-29 21:07
Looking at this closer after reading: https://docs.graphene-python.org/en/latest/types/enums/

I don't think we can have non-string based enum keys. You might be able to do: `kind_In: ["A_1", "A_2"]` as those are the generated enum keys.

This issue is probably a good example of why enums should be more opt-in.

**Comment by zbyte64** [comment] 2019-05-29 21:30
My recommendation to work around would be to explicitly define `kind`  at the `EventNode` without any enums as a plain integer field. It won't present choices but it would yield a more intuitive querying. Not sure how well that works with django filters though.

**Comment by changeling** [comment] 2019-05-30 15:52
The second issue, returning all records as failure mode, may be related to this issue:

https://github.com/graphql-python/graphene-django/issues/638

**Comment by zbyte64** [comment] 2019-05-31 17:46
Dupe of #67

**Closed by zbyte64** 2019-05-31 17:46 UTC
Labels: help wanted, 🐛bug
