### ISSUE TITLE
Convert DecimalField to String rather than Float

### ISSUE THREAD

**Issue by gsvr** [graphql-python/graphene-django#91] opened 2017-01-17 11:26 UTC
DecimalField entries are currently being converted to Float (https://github.com/graphql-python/graphene-django/blob/8f5a425859ea380d0640c441c5c7f3b1acae17b4/graphene_django/form_converter.py#L56-L59)

Full support for Decimal would be great, but in the meantime I propose that DecimalField should be converted to String instead. Once you've converted a Decimal to a Float, you've probably lost the benefit of why you used Decimal in the first place, since you'll now have values like `3.14000000000000012`, rather than `3.14`. If it is converted to String, it is simple enough for the user to convert that String back to Decimal, whereas converting from Float to Decimal is not straightforward.

**Comment by picturedots** [comment] 2017-06-01 16:09
As a workaround for this particular problem, I created a Decimal type, and then am explicitly setting that field in the DjangoObjectType class.  For example, I created a Decimal type like this

```
import decimal

from graphene.types import Scalar
from graphql.language import ast

class Decimal(Scalar):
    """ 
    The `Decimal` scalar type represents a python Decimal.
    """
    @staticmethod
    def serialize(dec):
        assert isinstance(dec, decimal.Decimal), (
            'Received not compatible Decimal "{}"'.format(repr(dec))
        )
        return str(dec)
    
    @staticmethod
    def parse_value(value):
        return decimal.Decimal(value)
    
    @classmethod
    def parse_literal(cls, node):
        if isinstance(node, ast.StringValue):
            return cls.parse_value(node.value)

```

and then explicitly replace the field like this:
```
class MyModelType(DjangoObjectType):
    my_decimal_field = Decimal()
    class Meta:
        model = MyModel
```
assuming that I have a Django model _MyModel_ with Decimal field _my_decimal_field_.

**Comment by zbyte64** [comment] 2018-10-19 18:35
Decimal type landed in graphene: https://github.com/graphql-python/graphene/issues/703

**Comment by picturedots** [comment] 2018-10-22 19:04
Yeah, I finally got around to adding my Decimal type into graphene.   It should be possible to fix graphene-django's implementation of DecimalField after the next release of graphene to actually use a Decimal, and it won't be necessary to convert to a **String** (as per the title of this issue).  Note that the JSON output is implemented as string though.

**Comment by gsvr** [comment] 2018-10-23 06:00
Brilliant, thank you @picturedots!

**Comment by picturedots** [comment] 2018-10-23 14:13
@gsvr  I didn't make the graphene-django change that you noted in form_converter.py above, so not sure if this is issue should be closed.  Without that change, it looks like Decimals are still explicitly converted to floats.

**Comment by clarkmoody** [comment] 2019-02-14 23:29
Waiting on this feature as well.

**Comment by ulgens** [comment] 2020-05-09 21:00
@gsvr @jkimbo Is this still relevant?

**Comment by ulgens** [comment] 2020-05-11 06:09
The issue is still relevant. We talked with @jkimbo about how to fix it. My work will be on https://github.com/graphql-python/graphene-django/pull/958 and i hope to complete in next couple days.

**Comment by gsvr** [comment] 2020-05-11 10:53
Thanks @ulgens 
I agree that it's still relevant - I've used a workaround in the meantime but this would be a good general improvement imho

**Closed** 2020-12-30 16:25 UTC
Labels: ✨enhancement

**Comment by gsvr** [comment] 2021-01-04 13:32
Thanks to everyone who contributed to resolving this! 👏 👏

**Comment by i6mi6** [comment] 2021-07-09 22:51
Has this been documented in the changelog? It broke our existing app logic because now suddenly we started getting strings rather than floats. Is there a way to default to previous behavior?

**Comment by beaugunderson** [comment] 2021-08-06 20:56
Huge +1 for adding a configuration setting for changing the default behavior here; it looks like this change happened in a minor release? It should have been a major release as it's a breaking change (it broke our codebase as well).

**Comment by i6mi6** [comment] 2021-08-06 21:02
@beaugunderson I ended up forking the repo then modifying it with this commit 
https://github.com/i6mi6/graphene-django/commit/d95b19daec7cafa0f3e772446cd7d4873040d2cc
In my case the branch name is `v2.15.0_decimal` then I added it to `requirements.txt` as follows:

```
...
graphene==2.1.8
git+git://github.com/i6mi6/graphene-django.git@v2.15.0_decimal#egg=graphene-django
...
```

**Comment by chidimo** [comment] 2021-11-15 09:51
> As a workaround for this particular problem, I created a Decimal type, and then am explicitly setting that field in the DjangoObjectType class. For example, I created a Decimal type like this
> 
> ```
> import decimal
> 
> from graphene.types import Scalar
> from graphql.language import ast
> 
> class Decimal(Scalar):
>     """ 
>     The `Decimal` scalar type represents a python Decimal.
>     """
>     @staticmethod
>     def serialize(dec):
>         assert isinstance(dec, decimal.Decimal), (
>             'Received not compatible Decimal "{}"'.format(repr(dec))
>         )
>         return str(dec)
>     
>     @staticmethod
>     def parse_value(value):
>         return decimal.Decimal(value)
>     
>     @classmethod
>     def parse_literal(cls, node):
>         if isinstance(node, ast.StringValue):
>             return cls.parse_value(node.value)
> ```
> 
> and then explicitly replace the field like this:
> 
> ```
> class MyModelType(DjangoObjectType):
>     my_decimal_field = Decimal()
>     class Meta:
>         model = MyModel
> ```
> 
> assuming that I have a Django model _MyModel_ with Decimal field _my_decimal_field_.

This approach is very helpful.
Thank you
