### ISSUE TITLE
ManyToMany relation with wrong type

### ISSUE THREAD

**Issue by amille44420** [graphql-python/graphene-django#253] opened 2017-08-21 14:23 UTC
I got into an issue with `DjangoObjectType` to convert a Django model into a GraphQL type ; On many to many relationships I get a list of the model owning the relation instead of the related model.

Here are the models to reproduce the issue

```python
from django.db import models

class Child(models.Model):
    pass

class Parent(models.Model):
    children = models.ManyToManyField(Child)
```

and the schema definition

```python
import graphene
from graphene_django import DjangoObjectType
from . import models

class Child(DjangoObjectType):
    class Meta:
        model = models.Child

class Parent(DjangoObjectType):
    class Meta:
        model = models.Parent

class Query(graphene.ObjectType):
    parents = graphene.List(Parent)

    def resolve_parents(self, args, context, info):
        return models.Parent.objects.all()

schema = graphene.Schema(query=Query)
```
And the test file

```python
import graphene
from django.test import TestCase
from graphene_django.fields import DjangoListField
from . import schema

class M2MTestCase(TestCase):
    def setUp(self):
        schema.schema.build_typemap()
        # get the graphql type for the field related to the children
        self.field_type = schema.Parent._meta.fields['children'].get_type()

    def test_graphql_types(self):
        # we must get a django list field
        self.assertEquals(isinstance(self.field_type, DjangoListField), True)
        # behind it we've a graphql list
        self.assertEquals(isinstance(self.field_type.type, graphene.List), True)
        # it must be a list of Child
        self.assertEquals(self.field_type.type.of_type, schema.Child)
```

**Comment by jsenecal** [comment] 2017-08-30 01:06
I actually have the same issue - have you found a workaround?

**Comment by jsenecal** [comment] 2017-08-30 01:13
I actually figured that this is a duplicate of https://github.com/graphql-python/graphene-django/issues/222 but with a different approach to the problem

**Comment by amille44420** [comment] 2017-08-30 15:06
So the only workaround I got is to override the definition myself

```python
class Parent(DjangoObjectType):
    children = graphene.List(User)

    class Meta:
        model = models.Parent
```

But I believe we should not have to do that to make it works.

**Comment by spockNinja** [comment] 2017-09-08 05:07
What version are you guys using? This should have been resolved by https://github.com/graphql-python/graphene-django/pull/181. However, it doesn't look like that fix was released until `2.0`. So if you're on a 1.X version, you might have to point to a specific commit or something in your pip requirements.

**Comment by dopeboy** [comment] 2019-05-23 16:36
@amille44420 were you able to try v2?

**Comment by ish-vasa** [comment] 2019-07-24 14:28
i'm on v2, django 2.3 and none of my m2m on my models autogenerate if that helps anyone

**Closed** 2019-09-29 15:19 UTC
Labels: wontfix
