### ISSUE TITLE
DjangoDebugMiddleware is not working with Django 1.10

### ISSUE THREAD

**Issue by Grmiade** [graphql-python/graphene-django#9] opened 2016-09-29 13:55 UTC
When I use `graphene_django.debug.DjangoDebugMiddleware` middleware, I have this error `TypeError: object() takes no parameters`. `graphene-django` doesn't support Django 1.10?

**Comment by stegben** [comment] 2016-10-22 07:24
Could you show detailed error messages?

**Comment by bcb** [comment] 2016-11-03 23:27
Can't reproduce this in Django 1.10.2. Possibly fixed.

**Comment by syrusakbary** [comment] 2016-11-04 03:09
Closing the issue as I'm unable to reproduce it either.
(Comment here or reopen if still happens).

**Closed by syrusakbary** 2016-11-04 03:09 UTC

**Comment by Grmiade** [comment] 2016-11-04 14:31
I always have this error :/ `TypeError: object() takes no parameters` with Django `1.10.3`
<img width="1174" alt="capture d ecran 2016-11-04 a 15 29 53" src="https://cloud.githubusercontent.com/assets/11244106/20009146/aa8331cc-a2a3-11e6-8616-e3e18ffdf77f.png">

**Comment by Grmiade** [comment] 2016-11-04 14:34
My fault .... :/ I added `graphene_django.debug.DjangoDebugMiddleware` in the `MIDDLEWARE` constant instead of `GRAPHENE` constant.
Sorry for that.
