### ISSUE TITLE
404 graphiql route

### ISSUE THREAD

**Issue by brandonmbanks** [graphql-python/graphene-django#683] opened 2019-06-20 02:16 UTC
I'm getting a 404 when going to `mysite/graphiql`. It is appending a slash to the url after not finding the route.

![image](https://user-images.githubusercontent.com/10030196/59813520-d62ac400-92df-11e9-9e5d-9a2785b0a67f.png)

Here are my urls:
```
urlpatterns = [
    path("admin/", admin.site.urls),
    path("graphql", ProtectedGraphQLView.as_view()),
    path("graphiql", GraphQLView.as_view(graphiql=True)),
]
```
If I changed `graphiql` to anything else it works.

```
urlpatterns = [
    path("admin/", admin.site.urls),
    path("graphql", ProtectedGraphQLView.as_view()),
    path("test", GraphQLView.as_view(graphiql=True)),
]
```
![image](https://user-images.githubusercontent.com/10030196/59813465-9368ec00-92df-11e9-8ee4-64ee528d9adf.png)
![image](https://user-images.githubusercontent.com/10030196/59813475-9d8aea80-92df-11e9-870c-775d0b10cccf.png)

Please let me know if you need any other information.

**Comment by brandonmbanks** [comment] 2019-06-20 02:19
Also if I append the `/` to the path, then I can pull it up.
```
path("graphiql", ProtectedGraphQLView.as_view()),
```
![image](https://user-images.githubusercontent.com/10030196/59813644-41749600-92e0-11e9-84c2-13914cbacbdc.png)
![image](https://user-images.githubusercontent.com/10030196/59813651-49343a80-92e0-11e9-9049-e8516d2a7558.png)

**Comment by brandonmbanks** [comment] 2019-06-20 10:54
Also I'm running 
Python 3.7.3
Django 2.2.2
Graphene 2.1.6 
Graphene Django 2.3.0

**Comment by phalt** [comment] 2019-06-20 16:03
Is this after upgrading django and or graphene-django or are you starting brand new?

This looks like you just got the URL config wrong.

**Comment by brandonmbanks** [comment] 2019-06-20 20:24
Started brand new. I don't think I got the config wrong. Again it works if I use any other string instead of `graphiql`

**Comment by phalt** [comment] 2019-06-21 08:37
I can't replicate this at all locally. I think this might be an issue with you Django URL configuration, not necessarily graphene-django. Can you check the [URLConf](https://docs.djangoproject.com/en/2.2/topics/http/urls/) docs and make sure you don't have anything wrong there?

**Comment by brandonmbanks** [comment] 2019-06-22 13:48
I can definitely do that.

**Comment by brandonmbanks** [comment] 2019-06-22 14:10
Really not sure what this issue is. Especially because any other string instead of graphiql works...

**Comment by jkimbo** [comment] 2019-06-24 09:52
@brandonmbanks Django is probably appending the slash to the url because of this setting: https://docs.djangoproject.com/en/2.2/ref/settings/#append-slash

But the underlying issue is that it is not resolving the `graphiql` route to begin with. I can't reproduce the issue locally when I replicate your URL patterns. Can you create a full reproducible example and push it to a repo somewhere?

**Comment by brandonmbanks** [comment] 2019-06-24 14:51
@jkimbo https://github.com/brandonmbanks/django-graphql-starter/tree/graphql-setup
I have it pushed up in a branch. Thanks for taking a look.

**Comment by jkimbo** [comment] 2019-06-24 15:18
@brandonmbanks I've tried that branch and it works fine for me:

<img width="357" alt="Screenshot 2019-06-24 16 15 57" src="https://user-images.githubusercontent.com/691952/60030740-6e87c680-969b-11e9-8c2c-4ba3bd8ff9cc.png">
<img width="669" alt="Screenshot 2019-06-24 16 16 09" src="https://user-images.githubusercontent.com/691952/60030744-70518a00-969b-11e9-8bdb-d8d4ccdd5293.png">

It's very odd but I don't think there is anything wrong with Graphene-Django. It has to be something to do with your setup (and something that is not in the code).

**Comment by brandonmbanks** [comment] 2019-06-24 17:08
Well I'm stumped. Looks like you didn't use the docker containers. I wonder if I might be missing something there.

**Comment by brandonmbanks** [comment] 2019-06-24 17:09
Why would it not find `graphiql` but then find `graphiql`. And why would `test` work just fine. So bizare to me.

**Comment by jkimbo** [comment] 2019-06-24 17:57
Yep I'm not sure what is going on sorry. I'm going to close this issue now since I'm pretty confident this is not an issue with Graphene-Django. Do report back if you find out the problem though!

**Closed by jkimbo** 2019-06-24 17:57 UTC
