### ISSUE TITLE
DjangoFormMutation input_field_name not work

### ISSUE THREAD

**Issue by elyashedayat0101** [graphql-python/graphene-django#1462] opened 2023-09-16 10:23 UTC
Hi everyone;
when i use from DjangoFromMutation arguements input_field_name not work correctly

**Comment by sjdemartini** [comment] 2023-09-16 16:04
@elyashedayat0101 When filing issues, please do not just delete or omit the original prompts from the GitHub issue templates. Instead, fully fill out the prompts so that we can understand exactly what is being asked, what you've tried, how to reproduce issues, what you feel is missing, etc. I'm going to close this out since there is simply not enough information to proceed, and you've added 3 separate issues of this type that do not provide enough context.

**Closed by sjdemartini** 2023-09-16 16:04 UTC
Labels: 🐛bug
