### ISSUE TITLE
graphene_django can't be imported without configuring Django settings

### ISSUE THREAD

**Issue by toolness** [graphql-python/graphene-django#500] opened 2018-08-19 13:51 UTC
When starting up a fresh Python interpreter, merely importing `graphene_django` raises an exception:

```
>>> import graphene_django
Traceback (most recent call last):
...
django.core.exceptions.ImproperlyConfigured: Requested setting DEBUG, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

While this doesn't seem like that big a deal (and in the grand scheme of things, it really isn't), it does break a few unexpected things.  For example, when I ran into some confusing things in the documentation (see #499), I tried examining the source using [pipenv](https://pipenv.readthedocs.io/en/latest/):

```bash
$ pipenv open graphene_django
Module not found!
```

This was super confusing, and admittedly might really be a bug in pipenv, but I assume it thought the module wasn't found because of the `ImproperlyConfigured` exception raised by importing `graphene_django`.

Anyways, if it's easy to change the package so that its root can be imported without requiring Django settings to be initialized, that would be helpful, but it's probably not really that big a deal if not.

**Comment by jayhale** [comment] 2018-08-19 14:33
Are you getting the interpreter from Django's shell initializer or just a new python session?

Generally with Django it's easiest to use a shell with Django already initialized (instead of having to call `django.setup()` yourself):

```sh
$ python manage.py shell
```

What's the use case for needing graphene-django without Django?  Many of the packages that require Django that I'm familiar with also require `django.setup()` before running - it seems to be a common pattern.

**Comment by toolness** [comment] 2018-08-19 14:59
So in my case it's really pipenv that's trying to imporat `graphene_django`--I'm not playing around in a shell myself, and perhaps I really should have titled this bug as "pipenv (and perhaps other tools like it) think graphene_django isn't installed".

It's also just a hunch on my part that pipenv thinks this because of the `ImproperlyConfigured` error that's being raised--I could be wrong.  So apologies for making a bunch of assumptions when filing this!

**Comment by jayhale** [comment] 2018-08-19 15:54
Can you create a clean repo to recreate the issue?  Happy to take a look.

`Module not found` indicates something may be wrong with your path.
`ImpropertlyConfigured` points to Django not being setup prior to being referenced.

**Comment by toolness** [comment] 2018-08-19 16:33
Sure, I can provide a repo, though doing this from the command-line works just as well:

```
mkdir graphene-django-issue-500-example
cd graphene-django-issue-500-example
pipenv install --python 3.7
pipenv install graphene-django
```

At this point you can open some of graphene-django's prerequisites in your editor:

```
pipenv open django
pipenv open graphene
```

Both of those should work.  However, the following will not:

```
pipenv open graphene_django
```

(changing the underscore to a hyphen doesn't fix things either.)

If you can't reproduce, or if you prefer a repo, let me know!

**Comment by jayhale** [comment] 2018-08-19 21:03
I think this goes back to having a minimal Django project present so that Django can be initialized. Even when running tests on a package that depends on Django, a valid Django configuration needs to be present for many Django imports to function.  Run `$ django-admin startproject graphene-django-issue-500-example` instead of just creating a new directory.

If that does't resolve it, then I would open the issue for pipenv and see if they can help.

**Comment by toolness** [comment] 2018-08-19 23:03
So the problem is that that doesn't resolve it, because pipenv doesn't know about project.settings. My point was just that it seems like a best practice to make a root package importable so that development tools like pipenv could import them without any prerequisites so they could get basic metadata out of them, such as the package's location...  (In contrast, for example, `pipenv open rest_framework` works fine, even though that package depends on Django too).  I think the most the pipenv folks can do is make it so the `ImproperlyConfigured` error propagates out instead of making pipenv erroneously report that the module isn't installed.

Anyways, thanks for your help!

**Comment by jayhale** [comment] 2018-08-20 15:27
If the issue is with Pipenv, please open an issue there.  Passing the error to the terminal would definitely be a feature request for Pipenv, not this library.  I recommend closing this and pursing the topic there.

**Comment by toolness** [comment] 2018-08-23 20:45
Well, so in my opinion, the issue is with _both_ Pipenv _and_ this library:

* Pipenv should not be reporting "module not found" when it gets an `ImproperlyConfigured` error when trying to import a module, it should just propagate the exception.

* The root module of third-party Django packages like this one should not be throwing an `ImproperlyConfigured` error when being imported, because it prevents development tools like Pipenv from discovering metadata about them, such as where they're located.  As a result, right now it's not possible for me to open this project's source code in my local editor via `pipenv open` unless I set `DJANGO_SETTINGS_MODULE` in my terminal environment, which is not (IMO) something Django developers should be expected to do.

**Comment by peterlandry** [comment] 2018-08-31 17:44
I just did a quick survey of some really common django packages, and all import cleanly without an active project, whereas `graphene-django` raises `ImproperlyConfigured`. I tend to agree that it should be possible to import without running `django.setup()`. It's a code smell to me that so much is being done on import of the package:

```✗ python
Python 3.7.0 (default, Aug 20 2018, 12:46:31)
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import graphene_django
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/peterlandry/Projects/server/.direnv/python-3.7.0/lib/python3.7/site-packages/graphene_django/__init__.py", line 1, in <module>
    from .types import DjangoObjectType
  File "/Users/peterlandry/Projects/server/.direnv/python-3.7.0/lib/python3.7/site-packages/graphene_django/types.py", line 9, in <module>
    from .converter import convert_django_field_with_choices
  File "/Users/peterlandry/Projects/server/.direnv/python-3.7.0/lib/python3.7/site-packages/graphene_django/converter.py", line 25, in <module>
    from .fields import DjangoListField, DjangoConnectionField
  File "/Users/peterlandry/Projects/server/.direnv/python-3.7.0/lib/python3.7/site-packages/graphene_django/fields.py", line 11, in <module>
    from .settings import graphene_settings
  File "/Users/peterlandry/Projects/server/.direnv/python-3.7.0/lib/python3.7/site-packages/graphene_django/settings.py", line 40, in <module>
    if settings.DEBUG:
  File "/Users/peterlandry/Projects/server/.direnv/python-3.7.0/lib/python3.7/site-packages/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/Users/peterlandry/Projects/server/.direnv/python-3.7.0/lib/python3.7/site-packages/django/conf/__init__.py", line 42, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting DEBUG, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.```

**Comment by peterlandry** [comment] 2018-08-31 17:57
I'm happy to work on a PR for this if the devs agree. It seems relatively simple to take the `DjangoObjectType` import out of `__init__.py`, it will be mostly documentation changes, if the devs agree.

**Comment by toolness** [comment] 2018-09-02 09:51
Thanks @peterlandry! I'm also happy to help in whatever way I can, if the devs agree.

**Comment by phalt** [comment] 2019-04-26 11:14
@toolness @peterlandry contributions welcome, I think having sensible defaults for the project settings will help.

**Closed** 2019-07-02 11:59 UTC
Labels: wontfix
