### ISSUE TITLE
CharField result is being returned capitalized

### ISSUE THREAD

**Issue by reverie** [graphql-python/graphene-django#564] opened 2018-12-26 18:34 UTC
I have a Django model with a `CharField(max_length=1)`. All the data on it stored in lowercase. In graphene, I have a `DjangoObjectType` query on that model. The value for the `CharField`, despite being stored in lowercase, is sent in graphene responses as uppercase, e.g. 'Y' instead of 'y'. I've even tried adding a resolve_foo method in my schema.py for that specific field. I return lowercase letters from there, and invariably they are returned capitalized on the wire. It's quite odd. Never had any trouble with other fields in my project. I tried setting a breakpoint in the resolve_foo method to see what might be altering the data further up the stack, but unfortunately there was a little too much going on internally for me to make sense of it.

**Comment by phalt** [comment] 2019-04-25 16:27
Hey @reverie - this could be a side-effect of the camel casing that graphene does to key names?

**Comment by reverie** [comment] 2019-04-25 19:23
@phalt No, it happens to the whole value on all `CharField`s that have a `choices` parameter.

**Comment by phalt** [comment] 2019-04-26 08:07
@reverie can you provide a code example to help us debug the issue?

**Comment by phalt** [comment] 2019-04-26 09:12
Duplicate of #67

**Closed by phalt** 2019-04-26 09:12 UTC
