### ISSUE TITLE
Support Django 3

### ISSUE THREAD

**Issue by Siecje** [graphql-python/graphene-django#771] opened 2019-09-10 16:16 UTC
`from django.utils import six` has been removed in Django version 3.

https://github.com/graphql-python/graphene-django/blob/master/graphene_django/settings.py#L18

**Comment by zbyte64** [comment] 2019-10-18 21:40
Dupe of #705

**Closed by zbyte64** 2019-10-18 21:40 UTC

**Comment by jkimbo** [comment] 2019-10-19 19:34
Not a dupe of #705 (because that is dealing with Graphene v3) but I think this was resolved in https://github.com/graphql-python/graphene-django/pull/793
