### ISSUE TITLE
Nullable BooleanField incorrectly mapped to GraphQL Boolean!

### ISSUE THREAD

**Issue by mjmare** [graphql-python/graphene-django#576] opened 2019-01-25 19:46 UTC
I have this in my Django model:
```
    some_boolean = models.BooleanField('The name',
                                             null=True,
                                             default=None,
                                             )
```
In GraphiQL this field is shown as:
```
someBoolean: Boolean!
```
and therefore I get an error: 
"message": "Cannot return null for non-nullable field ...someBoolean.",

**Comment by zbyte64** [comment] 2019-03-21 16:05
Duplicate of #486

**Closed by zbyte64** 2019-03-21 16:05 UTC
