### ISSUE TITLE
No support for deferred model proxies

### ISSUE THREAD

**Issue by serates** [graphql-python/graphene-django#346] opened 2017-12-14 22:11 UTC
Due to an extremely complex operation, i need to use a RawQuerySet, I am able to get past some lack of support for using raw query sets, however I haven't found a way to handle the type mismatch with a deferred object (this also would occur from a queryset that uses .only(),

I get the error message Expected value of type "MyModelNode" but got: MyModel_Deferred__.....

Is there any way for me to modify MyModelNode to accept defereed model instances?

**Comment by spockNinja** [comment] 2017-12-17 00:03
Thanks for the issue! There is a related discussion about proxy models in https://github.com/graphql-python/graphene-django/issues/319

Do you think the same solution would work for deferred proxies as well?

**Comment by serates** [comment] 2018-01-02 17:58
Sorry for the late response, was on holidays yes the solution in the linked issue should work for this too.

**Comment by phalt** [comment] 2019-04-26 13:00
Duplicate of #319

**Closed by phalt** 2019-04-26 13:00 UTC
