### ISSUE TITLE
Filtering on id using DjangoFilterConnectionField and use_connection

### ISSUE THREAD

**Issue by bendike** [graphql-python/graphene-django#1035] opened 2020-09-09 08:49 UTC
**When using DjangoFilterConnectionField with a type with `use_connection=True` (without global id) filtering on local id does not work. Filtering on global id does.**

Hi, sorry if this is a duplicate.

I think I have stumbled over some unintended behavior when using connections through `use_connection=True` paired with `django-filter` filter sets.

I have two django models and I want to be able to filter one based on the id of the other. A simplified setup is the following:

```python
class Product(models.Model):
    # more fields...

    location = models.ForeignKey(Location)


class Location(models.Model):
    # more fields...


class ProductGQLType(DjangoObjectType):
    class Meta:
        model = Product
        filterset_class = ProductFilterSet
        use_connection = True
        

class LocationGQLType(DjangoObjectType):
    class Meta:
        model = Location


class ProductFilterSet(FilterSet):
    class Meta:
        model = Product
        fields = [
            "location"
        ]

class Schema:
    products = DjangoFilterConnectionField(ProductGQLType, required=True)

```

So a query to filter products would be:
```js
products(first: 10, location: 123)
  edges {
    node {
      id
      location{
        id
      }
    }
  }
}
```

But this gives an error message "Invalid ID specified" for location. However if I base64 encode the location id and type (`location:123` encodes to `bG9jYXRpb246MTIz`) and use this for location input it gives expected result with, with the returned id for both types being the django object primary key (not relay global id).

I'm guessing this is related to the filter set mixin used for DjangoFilterConnectionField. I would think the intended behavior when using connections without global ids is to never handle global ids?

**Comment by bendike** [comment] 2020-09-09 09:06
It does not have to be a foreign key id. I managed to recreate with an even simpler setup: 
```python
class Product(models.Model):
    # some fields...

class ProductGQLType(DjangoObjectType):
    class Meta:
        model = Product
        filterset_class = ProductFilterSet
        use_connection = True

class ProductFilterSet(FilterSet):
    class Meta:
        model = Product
        fields = [
            "id"
        ]

class Schema:
    products = DjangoFilterConnectionField(ProductGQLType, required=True)
```

Querying with:
```js
products(first: 10, id: 123)
  edges {
    node {
      id
    }
  }
}
```
Gives the "Invalid ID specified" error, while if i encode to a global id it works.

**Comment by zbyte64** [comment] 2020-09-18 21:04
I think this is a duplicate of #957

**Closed by zbyte64** 2020-09-18 21:04 UTC
Labels: 🐛bug
