### ISSUE TITLE
Add autodoc-style API reference.

### ISSUE THREAD

**Issue by changeling** [graphql-python/graphene-django#650] opened 2019-05-25 21:49 UTC
It would be a tremendous boon for this and for all projects within the ecosystem here to add an autodoc API reference to the documentation. For other python libraries, this is, at least for me, the _most_ frequentlly used component of the docs. A PR for this has been submitted in the `graphene` repo, and should be duplicated, IMHO, here.

See https://github.com/graphql-python/graphene/pull/971

**Comment by jkimbo** [comment] 2019-07-28 15:54
Closing this as a duplicate of #679

**Closed by jkimbo** 2019-07-28 15:54 UTC
Labels: Docs enhancement, help wanted, wontfix
